version: '3'

services:
  database:
    image: postgres:alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${DB_REDIS_PASSWORD}"]
    container_name: redis-cache
    environment:
      REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
    ports:
      - "${DB_REDIS_PORT}:6379"
  jobs:
    build: ./jobs
    env_file: .env
    environment:
      - PORT=8181
      - ADDRESS_API=https://1afd-2804-1b3-af43-cde6-7df6-5368-ef23-2aab.ngrok-free.app
    container_name: jobs
    command: "npm start"
    working_dir: /home/node/app
    expose:
      - "8181"
    ports:
      - "8181:8181"
    depends_on:
      - database
      - redis

volumes:
  pgdata:
