
FROM node:20.5.1 AS builder

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY package*.json ./
USER node
RUN npm install

COPY --chown=node:node . .
RUN npm run build

FROM node:20.5.1

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --from=builder /home/node/app/dist ./dist
COPY --from=builder /home/node/app/package*.json ./

USER node
RUN npm install --only=production
EXPOSE 8181
CMD ["npm", "start"]
